<div class="form-group"><label for="titre">Titre <span class="text-danger">*</span></label><input type="text" name="titre" id="titre" class="form-control" value="{{ old('titre', $demarcheAdministrative->titre ?? '') }}" required></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label for="categorie">Catégorie</label><select name="categorie" id="categorie" class="form-control"><option value="creation">Création</option><option value="modification">Modification</option><option value="autorisation">Autorisation</option><option value="declaration">Déclaration</option><option value="agrement">Agrément</option><option value="certification">Certification</option><option value="enregistrement">Enregistrement</option><option value="radiation">Radiation</option></select></div></div><div class="col-md-6"><div class="form-group"><label for="slug">Slug</label><input type="text" name="slug" id="slug" class="form-control" value="{{ old('slug', $demarcheAdministrative->slug ?? '') }}" placeholder="Généré automatiquement"></div></div></div>
<div class="row"><div class="col-md-6"><div class="form-group"><label for="delai_estime">Délai estimé (jours)</label><input type="number" name="delai_estime" id="delai_estime" class="form-control" value="{{ old('delai_estime', $demarcheAdministrative->delai_estime ?? '') }}" min="1"></div></div><div class="col-md-6"><div class="form-group"><label for="cout_estime">Coût estimé (€)</label><input type="number" name="cout_estime" id="cout_estime" class="form-control" value="{{ old('cout_estime', $demarcheAdministrative->cout_estime ?? '') }}" step="0.01" min="0"></div></div></div>
<div class="form-group"><label for="description">Description</label><textarea name="description" id="description" rows="4" class="form-control">{{ old('description', $demarcheAdministrative->description ?? '') }}</textarea></div>
<div class="form-group"><label for="etapes">Étapes (JSON)</label><textarea name="etapes" id="etapes" rows="6" class="form-control font-monospace">{{ old('etapes', isset($demarcheAdministrative) && $demarcheAdministrative->etapes ? json_encode($demarcheAdministrative->etapes, JSON_PRETTY_PRINT) : '') }}</textarea><small class="text-muted">Format: [{"titre":"Étape 1","description":"Description","delai":5}]</small></div>
<div class="form-group"><label for="documents_requis">Documents requis (JSON)</label><textarea name="documents_requis" id="documents_requis" rows="3" class="form-control font-monospace">{{ old('documents_requis', isset($demarcheAdministrative) && $demarcheAdministrative->documents_requis ? json_encode($demarcheAdministrative->documents_requis, JSON_PRETTY_PRINT) : '') }}</textarea></div>
<div class="form-group"><label for="organismes">Organismes (JSON)</label><textarea name="organismes" id="organismes" rows="3" class="form-control font-monospace">{{ old('organismes', isset($demarcheAdministrative) && $demarcheAdministrative->organismes ? json_encode($demarcheAdministrative->organismes, JSON_PRETTY_PRINT) : '') }}</textarea></div>
<div class="form-group"><label for="url_officielle">URL officielle</label><input type="url" name="url_officielle" id="url_officielle" class="form-control" value="{{ old('url_officielle', $demarcheAdministrative->url_officielle ?? '') }}"></div>
<div class="form-group"><label for="notes">Notes internes</label><textarea name="notes" id="notes" rows="3" class="form-control">{{ old('notes', $demarcheAdministrative->notes ?? '') }}</textarea></div>
<div class="custom-control custom-switch"><input type="checkbox" name="is_active" id="is_active" class="custom-control-input" value="1" {{ old('is_active', $demarcheAdministrative->is_active ?? true) ? 'checked' : '' }}><label class="custom-control-label" for="is_active">Active</label></div>
@push('juridique-scripts')
<script>$('#titre').on('keyup', function() { if($('#slug').val() === '') $('#slug').val($(this).val().toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '')); });</script>
@endpush